#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use Release\Command\TagCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Yaml\Yaml;

$config = Yaml::parse(file_get_contents(__DIR__.'/../config.yml'));

$application = new Application('michel-tag', '1.0.0');
$command = new TagCommand($config);

$application->add($command);
$application->run();
